/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Clases.Menu;
import Clases.Mesas;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author krist
 */


public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    
    private ArrayList<Menu> lista = new ArrayList<Menu>();
    private ArrayList<Mesas> listams = new ArrayList<Mesas>();
    private Menu t;
    private Mesas m;
    private String id, nom, cate, numms, notas, pers, idmes;
    private int precio, pos;
    private boolean disp, ocp;
    private DefaultTableModel tablita;
    
    public Principal() {
        initComponents();
        ModifPlatos.pack();
        ModifPlatos.setLocationRelativeTo(null);
        ListarMesas.pack();
        ListarMesas.setLocationRelativeTo(null);
        ListaPlatos.pack();
        ListaPlatos.setLocationRelativeTo(null);
        ModifMesas.pack();
        ModifMesas.setLocationRelativeTo(null);
        
    }
    
    private void habilitardemas1(){
        TxtId.setEnabled(false);
        BtnBuscar.setEnabled(false);
        TxtNombre.setEnabled(true);
        BxCategoria.setEnabled(true);
        TxtPrecio.setEnabled(true);
        BtnDisponible.setEnabled(true);
        BtnNoDisponible.setEnabled(true);
        BtnGrdr.setEnabled(false);
        BtnModifCmb.setEnabled(true);
        BtnElimCmb.setEnabled(true);
        TxtNombre.requestFocus();  
    }
    
    private void habilitardemas2(){
        TxtId.setEnabled(false);
        BtnBuscar.setEnabled(false);
        TxtNombre.setEnabled(true);
        BxCategoria.setEnabled(true);
        TxtPrecio.setEnabled(true);
        BtnDisponible.setEnabled(true);
        BtnNoDisponible.setEnabled(true);
        BtnGrdr.setEnabled(true);
        BtnModifCmb.setEnabled(false);
        BtnElimCmb.setEnabled(false);
        TxtNombre.requestFocus(); 
    }
    
    private void habilitardemas3(){
        TxtNumMs.setEnabled(false);
        BtnBuscarMs1.setEnabled(false);
        TxtidMs.setEnabled(true);
        BxCatMs.setEnabled(true);
        TxtNotPlat.setEnabled(true);
        BtnMsSi.setEnabled(true);
        BtnMsNo.setEnabled(true);
        BtnGdrMs.setEnabled(false);
        BtnModifMs.setEnabled(true);
        BtnElimMs.setEnabled(true);
        TxtidMs.requestFocus();  
    }
    
    private void habilitardemas4(){
        TxtNumMs.setEnabled(false);
        BtnBuscarMs1.setEnabled(false);
        TxtidMs.setEnabled(true);
        BxCatMs.setEnabled(true);
        TxtNotPlat.setEnabled(true);
        BtnMsSi.setEnabled(true);
        BtnMsNo.setEnabled(true);
        BtnGdrMs.setEnabled(true);
        BtnModifMs.setEnabled(false);
        BtnElimMs.setEnabled(false);
        TxtidMs.requestFocus();  
    }
    
    private void vaciarcampos(){
        TxtId.setEnabled(true);
        BtnBuscar.setEnabled(true);
        TxtId.setText("");
        TxtNombre.setText("");
        TxtPrecio.setText("");
        BxCategoria.setSelectedIndex(0);
        BtnDisponible.setSelected(true);
        TxtNombre.setEnabled(false);
        BxCategoria.setEnabled(false);
        TxtPrecio.setEnabled(false);
        BtnDisponible.setEnabled(false);
        BtnNoDisponible.setEnabled(false);
        BtnGrdr.setEnabled(false);
        BtnModifCmb.setEnabled(false);
        BtnElimCmb.setEnabled(false);
        TxtId.requestFocus(); 
    }
    
    private void vaciarcampos2(){
        TxtNumMs.setEnabled(true);
        BtnBuscarMs1.setEnabled(true);
        TxtNumMs.setText("");
        TxtidMs.setText("");
        TxtNotPlat.setText("");
        BxCatMs.setSelectedIndex(0);
        BtnMsSi.setSelected(true);
        TxtidMs.setEnabled(false);
        TxtNotPlat.setEnabled(false);
        BxCatMs.setEnabled(false);
        BtnMsSi.setEnabled(false);
        BtnMsNo.setEnabled(false);
        BtnGdrMs.setEnabled(false);
        BtnModifMs.setEnabled(false);
        BtnElimMs.setEnabled(false);
        TxtNumMs.requestFocus(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ListaPlatos = new javax.swing.JFrame();
        tb_listarpl = new javax.swing.JScrollPane();
        TblPlatos = new javax.swing.JTable();
        LblNumPlt = new javax.swing.JLabel();
        LblPltDisp = new javax.swing.JLabel();
        LblNumCuantos = new javax.swing.JLabel();
        LblPlatCuantos = new javax.swing.JLabel();
        ModifPlatos = new javax.swing.JFrame();
        IdPlatos = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        Categoria = new javax.swing.JLabel();
        Precio = new javax.swing.JLabel();
        TxtId = new javax.swing.JTextField();
        TxtNombre = new javax.swing.JTextField();
        TxtPrecio = new javax.swing.JTextField();
        BtnBuscar = new javax.swing.JButton();
        Disponible = new javax.swing.JLabel();
        BtnDisponible = new javax.swing.JRadioButton();
        BtnNoDisponible = new javax.swing.JRadioButton();
        BxCategoria = new javax.swing.JComboBox<>();
        BtnGrdr = new javax.swing.JButton();
        TxtTitulo = new javax.swing.JLabel();
        BtnModifCmb = new javax.swing.JButton();
        BtnElimCmb = new javax.swing.JButton();
        ListarMesas = new javax.swing.JFrame();
        NbrMesa = new javax.swing.JLabel();
        TxtNbrMesa = new javax.swing.JTextField();
        EliOrdenMesa = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblOrdn = new javax.swing.JTable();
        CantPed = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        EliOrdenMesa1 = new javax.swing.JToggleButton();
        ModifMesas = new javax.swing.JFrame();
        BtnBuscarMs1 = new javax.swing.JButton();
        LblTitMs = new javax.swing.JLabel();
        LblidMs = new javax.swing.JLabel();
        LblOcpMs = new javax.swing.JLabel();
        BtnMsNo = new javax.swing.JRadioButton();
        BtnModifMs = new javax.swing.JButton();
        LblCatMs = new javax.swing.JLabel();
        LblNumMs = new javax.swing.JLabel();
        BxCatMs = new javax.swing.JComboBox<>();
        BtnMsSi = new javax.swing.JRadioButton();
        BtnNbrPlatMs = new javax.swing.JLabel();
        BtnElimMs = new javax.swing.JButton();
        TxtNumMs = new javax.swing.JTextField();
        BtnGdrMs = new javax.swing.JButton();
        TxtidMs = new javax.swing.JTextField();
        TxtNotPlat = new javax.swing.JTextField();
        GrpDispo = new javax.swing.ButtonGroup();
        GrpTermi = new javax.swing.ButtonGroup();
        NbrRst = new javax.swing.JLabel();
        MsjRst = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        BarradeTareas = new javax.swing.JMenuBar();
        BtnTrMenu = new javax.swing.JMenu();
        BtnPlatos = new javax.swing.JMenuItem();
        BtnModifPlts = new javax.swing.JMenuItem();
        BtnTrMesas = new javax.swing.JMenu();
        BtnListarMesas = new javax.swing.JMenuItem();
        BtnModifMesas = new javax.swing.JMenuItem();

        ListaPlatos.setTitle("Lista de Platos");

        TblPlatos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TblPlatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id Plato", "Nombre", "Categoria", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_listarpl.setViewportView(TblPlatos);

        LblNumPlt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblNumPlt.setText("Numero de Platos :");

        LblPltDisp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblPltDisp.setText("Platillos Disponibles :");

        LblNumCuantos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblNumCuantos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblNumCuantos.setText("0");
        LblNumCuantos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        LblPlatCuantos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblPlatCuantos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblPlatCuantos.setText("0");
        LblPlatCuantos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout ListaPlatosLayout = new javax.swing.GroupLayout(ListaPlatos.getContentPane());
        ListaPlatos.getContentPane().setLayout(ListaPlatosLayout);
        ListaPlatosLayout.setHorizontalGroup(
            ListaPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaPlatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ListaPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tb_listarpl, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
                    .addGroup(ListaPlatosLayout.createSequentialGroup()
                        .addGroup(ListaPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(LblPltDisp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LblNumPlt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ListaPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblNumCuantos, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblPlatCuantos, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 670, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ListaPlatosLayout.setVerticalGroup(
            ListaPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaPlatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tb_listarpl, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ListaPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblNumPlt)
                    .addComponent(LblNumCuantos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ListaPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblPltDisp)
                    .addComponent(LblPlatCuantos))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        ModifPlatos.setTitle("Modificar Platos");
        ModifPlatos.setResizable(false);

        IdPlatos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        IdPlatos.setText("Id Plato");

        Nombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Nombre.setText("Nombre ");

        Categoria.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Categoria.setText("Categoria");

        Precio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Precio.setText("Precio");

        TxtNombre.setEnabled(false);
        TxtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombreActionPerformed(evt);
            }
        });

        TxtPrecio.setEnabled(false);
        TxtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPrecioActionPerformed(evt);
            }
        });

        BtnBuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnBuscar.setText("Buscar");
        BtnBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });

        Disponible.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Disponible.setText("Disponible");

        GrpDispo.add(BtnDisponible);
        BtnDisponible.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnDisponible.setText("Disponible");
        BtnDisponible.setEnabled(false);
        BtnDisponible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDisponibleActionPerformed(evt);
            }
        });

        GrpDispo.add(BtnNoDisponible);
        BtnNoDisponible.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnNoDisponible.setText("No Disponible");
        BtnNoDisponible.setEnabled(false);

        BxCategoria.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bebida", "Entrada", "Plato Fuerte", "Postre" }));
        BxCategoria.setEnabled(false);

        BtnGrdr.setText("Guardar Cambios");
        BtnGrdr.setEnabled(false);
        BtnGrdr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGrdrActionPerformed(evt);
            }
        });

        TxtTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TxtTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtTitulo.setText("Modificar Platos");

        BtnModifCmb.setText("Modificar Cambios");
        BtnModifCmb.setEnabled(false);
        BtnModifCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModifCmbActionPerformed(evt);
            }
        });

        BtnElimCmb.setText("Eliminar Cambios");
        BtnElimCmb.setEnabled(false);
        BtnElimCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnElimCmbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ModifPlatosLayout = new javax.swing.GroupLayout(ModifPlatos.getContentPane());
        ModifPlatos.getContentPane().setLayout(ModifPlatosLayout);
        ModifPlatosLayout.setHorizontalGroup(
            ModifPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModifPlatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ModifPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModifPlatosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(ModifPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Disponible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(IdPlatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Categoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Precio, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ModifPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(ModifPlatosLayout.createSequentialGroup()
                                .addComponent(TxtId, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnBuscar))
                            .addComponent(TxtNombre)
                            .addComponent(TxtPrecio, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ModifPlatosLayout.createSequentialGroup()
                                .addComponent(BtnDisponible)
                                .addGap(18, 18, 18)
                                .addComponent(BtnNoDisponible))
                            .addComponent(BxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModifPlatosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ModifPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnElimCmb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnModifCmb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnGrdr, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        ModifPlatosLayout.setVerticalGroup(
            ModifPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModifPlatosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(TxtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ModifPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TxtId)
                    .addComponent(IdPlatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ModifPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ModifPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ModifPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Precio, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ModifPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(Disponible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnDisponible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnNoDisponible))
                .addGap(18, 18, 18)
                .addComponent(BtnGrdr, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnModifCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnElimCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        ListarMesas.setTitle("Lista de Mesas");
        ListarMesas.setResizable(false);

        NbrMesa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NbrMesa.setText("Ingrese el Numero de Mesa:");

        TxtNbrMesa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TxtNbrMesa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        EliOrdenMesa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        EliOrdenMesa.setText("Buscar");

        TblOrdn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TblOrdn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TblOrdn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Ordenes", "Sillas Ocupadas", "Mesero Asignado", "Pedidos Especiales"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TblOrdn.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TblOrdn);

        CantPed.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CantPed.setText("Cantidad Total de Pedidos :");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("0");

        EliOrdenMesa1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        EliOrdenMesa1.setText("Eliminar");

        javax.swing.GroupLayout ListarMesasLayout = new javax.swing.GroupLayout(ListarMesas.getContentPane());
        ListarMesas.getContentPane().setLayout(ListarMesasLayout);
        ListarMesasLayout.setHorizontalGroup(
            ListarMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListarMesasLayout.createSequentialGroup()
                .addGroup(ListarMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ListarMesasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(ListarMesasLayout.createSequentialGroup()
                        .addGroup(ListarMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ListarMesasLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(CantPed, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ListarMesasLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(NbrMesa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtNbrMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EliOrdenMesa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EliOrdenMesa1)))
                        .addGap(0, 339, Short.MAX_VALUE)))
                .addContainerGap())
        );

        ListarMesasLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {EliOrdenMesa, EliOrdenMesa1});

        ListarMesasLayout.setVerticalGroup(
            ListarMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListarMesasLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(ListarMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NbrMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListarMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TxtNbrMesa)
                        .addComponent(EliOrdenMesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EliOrdenMesa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ListarMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CantPed)
                    .addComponent(jLabel1))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        ListarMesasLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {EliOrdenMesa, EliOrdenMesa1, NbrMesa, TxtNbrMesa});

        ModifMesas.setTitle("Modificar Mesas");
        ModifMesas.setResizable(false);

        BtnBuscarMs1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnBuscarMs1.setText("Buscar");
        BtnBuscarMs1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnBuscarMs1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarMs1ActionPerformed(evt);
            }
        });

        LblTitMs.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LblTitMs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblTitMs.setText("Modificar Mesas");

        LblidMs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblidMs.setText("Id Mesero");

        LblOcpMs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblOcpMs.setText("Ocupada");

        GrpDispo.add(BtnMsNo);
        BtnMsNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnMsNo.setText("No");
        BtnMsNo.setEnabled(false);

        BtnModifMs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnModifMs.setText("Modificar Cambios");
        BtnModifMs.setEnabled(false);
        BtnModifMs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModifMsActionPerformed(evt);
            }
        });

        LblCatMs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblCatMs.setText("Personas");

        LblNumMs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblNumMs.setText("Numero de Mesa");

        BxCatMs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BxCatMs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vacia", "1 Persona", "2 Personas", "3 Personas", "4 Personas", "5 Personas", "6 Personas" }));
        BxCatMs.setEnabled(false);
        BxCatMs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BxCatMsActionPerformed(evt);
            }
        });

        GrpDispo.add(BtnMsSi);
        BtnMsSi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnMsSi.setText("Si");
        BtnMsSi.setEnabled(false);
        BtnMsSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMsSiActionPerformed(evt);
            }
        });

        BtnNbrPlatMs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnNbrPlatMs.setText("Notas");

        BtnElimMs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnElimMs.setText("Eliminar Cambios");
        BtnElimMs.setEnabled(false);
        BtnElimMs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnElimMsActionPerformed(evt);
            }
        });

        TxtNumMs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNumMsActionPerformed(evt);
            }
        });

        BtnGdrMs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnGdrMs.setText("Guardar Cambios");
        BtnGdrMs.setEnabled(false);
        BtnGdrMs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGdrMsActionPerformed(evt);
            }
        });

        TxtidMs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TxtidMs.setEnabled(false);
        TxtidMs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtidMsActionPerformed(evt);
            }
        });

        TxtNotPlat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TxtNotPlat.setEnabled(false);
        TxtNotPlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNotPlatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ModifMesasLayout = new javax.swing.GroupLayout(ModifMesas.getContentPane());
        ModifMesas.getContentPane().setLayout(ModifMesasLayout);
        ModifMesasLayout.setHorizontalGroup(
            ModifMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModifMesasLayout.createSequentialGroup()
                .addGroup(ModifMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModifMesasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(ModifMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnGdrMs, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModifMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(BtnModifMs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnElimMs, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20))
                    .addGroup(ModifMesasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ModifMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblTitMs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModifMesasLayout.createSequentialGroup()
                                .addGroup(ModifMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(ModifMesasLayout.createSequentialGroup()
                                        .addGroup(ModifMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(BtnNbrPlatMs, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LblCatMs, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LblidMs, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(ModifMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(BxCatMs, 0, 322, Short.MAX_VALUE)
                                            .addComponent(TxtNotPlat, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(TxtidMs)))
                                    .addGroup(ModifMesasLayout.createSequentialGroup()
                                        .addComponent(LblNumMs)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtNumMs)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BtnBuscarMs1)))
                                .addGap(4, 4, 4)))))
                .addContainerGap())
            .addGroup(ModifMesasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblOcpMs, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnMsSi)
                .addGap(18, 18, 18)
                .addComponent(BtnMsNo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ModifMesasLayout.setVerticalGroup(
            ModifMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModifMesasLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(LblTitMs, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ModifMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ModifMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LblNumMs, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                        .addComponent(TxtNumMs))
                    .addGroup(ModifMesasLayout.createSequentialGroup()
                        .addComponent(BtnBuscarMs1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ModifMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtidMs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblidMs))
                .addGap(3, 3, 3)
                .addGroup(ModifMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BxCatMs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblCatMs, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(ModifMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ModifMesasLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(BtnNbrPlatMs))
                    .addGroup(ModifMesasLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtNotPlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ModifMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ModifMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                        .addComponent(BtnMsSi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnMsNo))
                    .addComponent(LblOcpMs))
                .addGap(31, 31, 31)
                .addComponent(BtnGdrMs, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnModifMs, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnElimMs, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        ModifMesasLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {BtnNbrPlatMs, LblCatMs, LblOcpMs, LblidMs});

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kazza");
        setBackground(new java.awt.Color(0, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        NbrRst.setFont(new java.awt.Font("Imprint MT Shadow", 1, 48)); // NOI18N
        NbrRst.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NbrRst.setText("Kazza");

        MsjRst.setFont(new java.awt.Font("Imprint MT Shadow", 1, 18)); // NOI18N
        MsjRst.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MsjRst.setText("L'autentico sapore italiano");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        BarradeTareas.setBackground(new java.awt.Color(51, 51, 51));
        BarradeTareas.setForeground(new java.awt.Color(0, 0, 0));

        BtnTrMenu.setBackground(new java.awt.Color(255, 255, 255));
        BtnTrMenu.setForeground(new java.awt.Color(0, 0, 0));
        BtnTrMenu.setText("Menu");
        BtnTrMenu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        BtnPlatos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        BtnPlatos.setText("Lista de Platos");
        BtnPlatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPlatosActionPerformed(evt);
            }
        });
        BtnTrMenu.add(BtnPlatos);

        BtnModifPlts.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        BtnModifPlts.setText("Modificar Platos");
        BtnModifPlts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModifPltsActionPerformed(evt);
            }
        });
        BtnTrMenu.add(BtnModifPlts);

        BarradeTareas.add(BtnTrMenu);

        BtnTrMesas.setText("Mesas");
        BtnTrMesas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnTrMesas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        BtnListarMesas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        BtnListarMesas.setText("Listar Mesas");
        BtnListarMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnListarMesasActionPerformed(evt);
            }
        });
        BtnTrMesas.add(BtnListarMesas);

        BtnModifMesas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        BtnModifMesas.setText("Modificar Mesas");
        BtnModifMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModifMesasActionPerformed(evt);
            }
        });
        BtnTrMesas.add(BtnModifMesas);

        BarradeTareas.add(BtnTrMesas);

        setJMenuBar(BarradeTareas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(NbrRst, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(150, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MsjRst, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(NbrRst, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MsjRst, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnModifPltsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModifPltsActionPerformed
        ModifPlatos.setVisible(true);
    }//GEN-LAST:event_BtnModifPltsActionPerformed

    private void TxtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrecioActionPerformed

    private void TxtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNombreActionPerformed

    private void BtnDisponibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDisponibleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnDisponibleActionPerformed

    private void BtnListarMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnListarMesasActionPerformed
        ListarMesas.setVisible(true);
    }//GEN-LAST:event_BtnListarMesasActionPerformed

    private void BtnPlatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPlatosActionPerformed
        ListaPlatos.setVisible(true);
    }//GEN-LAST:event_BtnPlatosActionPerformed

    private void BtnModifMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModifMesasActionPerformed
        ModifMesas.setVisible(true);
    }//GEN-LAST:event_BtnModifMesasActionPerformed

    private void BtnBuscarMs1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarMs1ActionPerformed
        //Boton Buscar Mesas
        if(TxtNumMs.getText().trim().isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(null,"EL Campo esta Vacio","ERROR",2);
            TxtNumMs.setText("");
            TxtNumMs.requestFocus();
        }else {
            numms = TxtNumMs.getText();
            ocp = false;
            for (int i = 0; i < listams.size(); i++) {
                m = listams.get(i);
                if (numms.equalsIgnoreCase(m.getNumesa())) {
                    ocp = true;
                    habilitardemas3();
                    TxtidMs.setText(m.getIdmes());
                    BxCatMs.setSelectedItem(m.getPers());
                    TxtNotPlat.setText(m.getNots());
                    if(ocp == true){
                        BtnMsSi.setSelected(true);
                    }else{
                        BtnMsNo.setSelected(true);
                    }
                    javax.swing.JOptionPane.showMessageDialog(null,"Mesa Encontrada","Accion Finalizada",1);
                    break;
                }
            }
            if(ocp == false){
                javax.swing.JOptionPane.showMessageDialog(null,"Puede Ingresar una Nueva Mesa o Intentarlo de Nuevo","Numero de Mesa No Encontrado",3);
                habilitardemas4();
            }
        }
    }//GEN-LAST:event_BtnBuscarMs1ActionPerformed

    private void BtnMsSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMsSiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnMsSiActionPerformed

    private void TxtNumMsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNumMsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNumMsActionPerformed

    private void TxtidMsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtidMsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtidMsActionPerformed

    private void BxCatMsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BxCatMsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BxCatMsActionPerformed

    private void BtnModifMsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModifMsActionPerformed
        // Boton Modificar Cambios Mesas
        if(TxtNumMs.getText().trim().isEmpty() || TxtidMs.getText().trim().isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(null,"Datos Insuficientes","ERROR",2);
        }else{
            numms = TxtNumMs.getText();
            notas = TxtNotPlat.getText();
            idmes = TxtidMs.getText();
            pers = BxCatMs.getSelectedItem().toString();
            switch(pers){
                case "Vacia":
                    break;
                case "1 Persona":
                    break;
                case "2 Personas":
                    break;
                case "3 Personas":
                    break;
                case "4 Personas":
                    break;
                case "5 Personas":
                    break;
                case "6 Personas":
                    break;
            }//termina switch
            
            if(BtnMsSi.isSelected()){
                ocp = true;
            }else{
                ocp = false;
            }
        }
        m = new Mesas();
        m.setNumesa(numms);
        m.setNots(notas);
        m.setIdmes(idmes);
        m.setPers(pers);
        m.setOcup(ocp);
        listams.add(m);
        
        javax.swing.JOptionPane.showMessageDialog(null,"La Mesa fue Modificada","Accion Finalizada",1);
        
        int pos = ObtenerPosicion(numms);
        listams.set(pos, m);
        javax.swing.JOptionPane.showMessageDialog(null, "La Mesa fue Modificado", "Accion Finalizada", 1);
        vaciarcampos2();
    }//GEN-LAST:event_BtnModifMsActionPerformed

    private void BtnElimMsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnElimMsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnElimMsActionPerformed

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        // Boton Buscar Platos
        if(TxtId.getText().trim().isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(null,"EL Campo esta Vacio","ERROR",2);
            TxtId.setText("");
            TxtId.requestFocus();
        }else {
            id = TxtId.getText();
            disp = false;
            for (int i = 0; i < lista.size(); i++) {
                t = lista.get(i);
                if (id.equalsIgnoreCase(t.getIdplato())) {
                    disp = true;
                    habilitardemas1();
                    TxtNombre.setText(t.getNombre());
                    BxCategoria.setSelectedItem(t.getCategoria());
                    TxtPrecio.setText(Integer.toString(t.getPrecio()));
                    if(disp == true){
                        BtnDisponible.setSelected(true);
                    }else{
                        BtnNoDisponible.setSelected(true);
                    }
                    javax.swing.JOptionPane.showMessageDialog(null,"Id Encontrado","Accion Finalizada",1);
                    break;
                }
            }
            if(disp == false){
                javax.swing.JOptionPane.showMessageDialog(null,"Puede Ingresar un Nuevo Plato o Intentarlo de Nuevo","Id No Encontrado",3);
                habilitardemas2();
            }
        }
    }//GEN-LAST:event_BtnBuscarActionPerformed

    private void BtnGrdrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGrdrActionPerformed
        // Boton Guardar Platos
        if(TxtNombre.getText().trim().isEmpty() || TxtPrecio.getText().trim().isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(null,"Datos Insuficientes","ERROR",2);
        }else{
            int id = idrandom();
            TxtId.setText(Integer.toString(id));
            nom = TxtNombre.getText();
            precio = Integer.parseInt(TxtPrecio.getText());
            cate = BxCategoria.getSelectedItem().toString();
            switch(cate){
                case "Bebida":
                    break;
                case "Entrada":
                    break;
                case "Plato Fuerte":
                    break;
                case "Postre":
                    break;
            }//termina switch
            
            if(BtnDisponible.isSelected()){
                disp = true;
            }else{
                disp = false;
            }
        }
        t = new Menu();
        t.setIdplato(id);
        t.setIdplato(id);
        t.setNombre(nom);
        t.setCategoria(cate);
        t.setPrecio(precio);
        t.setDisponible(disp);
        lista.add(t);
        javax.swing.JOptionPane.showMessageDialog(null,"El Plato fue Ingresado","Accion Finalizada",1);
        vaciarcampos();
    }//GEN-LAST:event_BtnGrdrActionPerformed

    private void BtnModifCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModifCmbActionPerformed
        // Boton Modificar Cambios Platos
        if (TxtNombre.getText().trim().isEmpty() || TxtPrecio.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Datos Insuficientes", "ERROR", 2);
        } else {
            int id = idrandom();
            TxtId.setText(Integer.toString(id));
            nom = TxtNombre.getText();
            precio = Integer.parseInt(TxtPrecio.getText());
            cate = BxCategoria.getSelectedItem().toString();
            switch (cate) {
                case "Bebida":
                    break;
                case "Entrada":
                    break;
                case "Plato Fuerte":
                    break;
                case "Postre":
                    break;
            }//termina switch

            if (BtnDisponible.isSelected()) {
                disp = true;
            } else {
                disp = false;
            }
        }
        t = new Menu();
        t.setIdplato(id);
        t.setNombre(nom);
        t.setCategoria(cate);
        t.setPrecio(precio);
        t.setDisponible(disp);
        
        int pos = ObtenerPosicion(id);
        lista.set(pos, t);
        javax.swing.JOptionPane.showMessageDialog(null, "El Plato fue Modificado", "Accion Finalizada", 1);
        vaciarcampos();

    }//GEN-LAST:event_BtnModifCmbActionPerformed

    private void BtnElimCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnElimCmbActionPerformed
        // Boton Eliminar Cambios Platos
        id = TxtId.getText();
        int pos = ObtenerPosicion(id);
        lista.remove(pos);
        javax.swing.JOptionPane.showMessageDialog(null, "El Plato fue Eliminado", "Accion Finalizada", 1);
        vaciarcampos();
    }//GEN-LAST:event_BtnElimCmbActionPerformed

    private void BtnGdrMsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGdrMsActionPerformed
        //Boton Guardar Mesas
        if(TxtNumMs.getText().trim().isEmpty() || TxtidMs.getText().trim().isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(null,"Datos Insuficientes","ERROR",2);
        }else{
            numms = TxtNumMs.getText();
            notas = TxtNotPlat.getText();
            int idmes = idrandom();
            TxtidMs.setText(Integer.toString(idmes));
            pers = BxCatMs.getSelectedItem().toString();
            switch(pers){
                case "Vacia":
                    break;
                case "1 Persona":
                    break;
                case "2 Personas":
                    break;
                case "3 Personas":
                    break;
                case "4 Personas":
                    break;
                case "5 Personas":
                    break;
                case "6 Personas":
                    break;
            }//termina switch
            
            if(BtnMsSi.isSelected()){
                ocp = true;
            }else{
                ocp = false;
            }
        }
        m = new Mesas();
        m.setNumesa(numms);
        m.setNots(notas);
        m.setIdmes(idmes);
        m.setPers(pers);
        m.setOcup(ocp);
        listams.add(m);
        javax.swing.JOptionPane.showMessageDialog(null,"La Mesa fue Guardada","Accion Finalizada",1);
        vaciarcampos2();
    }//GEN-LAST:event_BtnGdrMsActionPerformed

    private void TxtNotPlatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNotPlatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNotPlatActionPerformed

    private int idrandom() {
        Random random = new Random();
        return random.nextInt(50) + 1;
    }
    
    private int ObtenerPosicion(String Id) {
        for (int i = 0; i < lista.size(); i++) {
            Menu t = lista.get(i);
            if (Id.equalsIgnoreCase(t.getIdplato())) {
                return i;
            }
        }
        return -1;
    }
    
    private void listarplatos(){
        tablita = (DefaultTableModel) TblPlatos.getModel();
        for (int i = 0; i < lista.size(); i++) {
            t = lista.get(i);
            tablita.addRow(new Object []{
                t.getIdplato(),
                t.getNombre(),
                t.getCategoria(),
                t.getPrecio()
            });
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Principal principal = new Principal();
                principal.pack();
                principal.setVisible(true);
                principal.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarradeTareas;
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnBuscarMs1;
    private javax.swing.JRadioButton BtnDisponible;
    private javax.swing.JButton BtnElimCmb;
    private javax.swing.JButton BtnElimMs;
    private javax.swing.JButton BtnGdrMs;
    private javax.swing.JButton BtnGrdr;
    private javax.swing.JMenuItem BtnListarMesas;
    private javax.swing.JButton BtnModifCmb;
    private javax.swing.JMenuItem BtnModifMesas;
    private javax.swing.JButton BtnModifMs;
    private javax.swing.JMenuItem BtnModifPlts;
    private javax.swing.JRadioButton BtnMsNo;
    private javax.swing.JRadioButton BtnMsSi;
    private javax.swing.JLabel BtnNbrPlatMs;
    private javax.swing.JRadioButton BtnNoDisponible;
    private javax.swing.JMenuItem BtnPlatos;
    private javax.swing.JMenu BtnTrMenu;
    private javax.swing.JMenu BtnTrMesas;
    private javax.swing.JComboBox<String> BxCatMs;
    private javax.swing.JComboBox<String> BxCategoria;
    private javax.swing.JLabel CantPed;
    private javax.swing.JLabel Categoria;
    private javax.swing.JLabel Disponible;
    private javax.swing.JToggleButton EliOrdenMesa;
    private javax.swing.JToggleButton EliOrdenMesa1;
    private javax.swing.ButtonGroup GrpDispo;
    private javax.swing.ButtonGroup GrpTermi;
    private javax.swing.JLabel IdPlatos;
    private javax.swing.JLabel LblCatMs;
    private javax.swing.JLabel LblNumCuantos;
    private javax.swing.JLabel LblNumMs;
    private javax.swing.JLabel LblNumPlt;
    private javax.swing.JLabel LblOcpMs;
    private javax.swing.JLabel LblPlatCuantos;
    private javax.swing.JLabel LblPltDisp;
    private javax.swing.JLabel LblTitMs;
    private javax.swing.JLabel LblidMs;
    private javax.swing.JFrame ListaPlatos;
    private javax.swing.JFrame ListarMesas;
    private javax.swing.JFrame ModifMesas;
    private javax.swing.JFrame ModifPlatos;
    private javax.swing.JLabel MsjRst;
    private javax.swing.JLabel NbrMesa;
    private javax.swing.JLabel NbrRst;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Precio;
    private javax.swing.JTable TblOrdn;
    private javax.swing.JTable TblPlatos;
    private javax.swing.JTextField TxtId;
    private javax.swing.JTextField TxtNbrMesa;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtNotPlat;
    private javax.swing.JTextField TxtNumMs;
    private javax.swing.JTextField TxtPrecio;
    private javax.swing.JLabel TxtTitulo;
    private javax.swing.JTextField TxtidMs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane tb_listarpl;
    // End of variables declaration//GEN-END:variables
}
