/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

/**
 *
 * @author krist
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        ModifPlatos.pack();
        ModifPlatos.setLocationRelativeTo(null);
        ModifEmpleados.pack();
        ModifEmpleados.setLocationRelativeTo(null);
        ListarMesas.pack();
        ListarMesas.setLocationRelativeTo(null);
        ListaPlatos.pack();
        ListaPlatos.setLocationRelativeTo(null);
        ModifMesas.pack();
        ModifMesas.setLocationRelativeTo(null);
        FrmNuestraHistoria.pack();
        FrmNuestraHistoria.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ListaPlatos = new javax.swing.JFrame();
        LabCate = new javax.swing.JLabel();
        GrpTxtCate = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        TblPlatos = new javax.swing.JTable();
        LblNumPlt = new javax.swing.JLabel();
        LblPltDisp = new javax.swing.JLabel();
        LblNumCuantos = new javax.swing.JLabel();
        LblPlatCuantos = new javax.swing.JLabel();
        ModifPlatos = new javax.swing.JFrame();
        IdPlatos = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        Categoria = new javax.swing.JLabel();
        Precio = new javax.swing.JLabel();
        TxtId = new javax.swing.JTextField();
        TxtNombre = new javax.swing.JTextField();
        TxtPrecio = new javax.swing.JTextField();
        BtnBuscar = new javax.swing.JButton();
        Disponible = new javax.swing.JLabel();
        BtnDisponible = new javax.swing.JRadioButton();
        BtnNoDisponible = new javax.swing.JRadioButton();
        BxCategoria = new javax.swing.JComboBox<>();
        BtnGrdr = new javax.swing.JButton();
        TxtTitulo = new javax.swing.JLabel();
        BtnModifCmb = new javax.swing.JButton();
        BtnElimCmb = new javax.swing.JButton();
        GrpDispo = new javax.swing.ButtonGroup();
        ModifEmpleados = new javax.swing.JFrame();
        Nombre1 = new javax.swing.JLabel();
        BtnNo = new javax.swing.JRadioButton();
        Tarea = new javax.swing.JLabel();
        BxTarea = new javax.swing.JComboBox<>();
        Turno = new javax.swing.JLabel();
        TxtId1 = new javax.swing.JTextField();
        BtnGrdr1 = new javax.swing.JButton();
        TxtNombre1 = new javax.swing.JTextField();
        TxtTurno1 = new javax.swing.JTextField();
        BtnBuscar1 = new javax.swing.JButton();
        TxtTitulo1 = new javax.swing.JLabel();
        Presente1 = new javax.swing.JLabel();
        BtnModifCmb1 = new javax.swing.JButton();
        IdEmpleados1 = new javax.swing.JLabel();
        BtnSi1 = new javax.swing.JRadioButton();
        BtnElimCmb1 = new javax.swing.JButton();
        ListarMesas = new javax.swing.JFrame();
        NbrMesa = new javax.swing.JLabel();
        TxtNbrMesa = new javax.swing.JTextField();
        EliOrdenMesa = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblOrdn = new javax.swing.JTable();
        CantPed = new javax.swing.JLabel();
        TermiServ = new javax.swing.JLabel();
        BtnTermiSi = new javax.swing.JRadioButton();
        BtnTermiNo = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        EliOrdenMesa1 = new javax.swing.JToggleButton();
        GrpTermi = new javax.swing.ButtonGroup();
        ModifMesas = new javax.swing.JFrame();
        BtnBuscarMs1 = new javax.swing.JButton();
        LblTitMs = new javax.swing.JLabel();
        LblidMs = new javax.swing.JLabel();
        LblOcpMs = new javax.swing.JLabel();
        BtnMsNo = new javax.swing.JRadioButton();
        BtnModifMs = new javax.swing.JButton();
        LblCatMs = new javax.swing.JLabel();
        LblNumMs = new javax.swing.JLabel();
        BxCatMs = new javax.swing.JComboBox<>();
        BtnMsSi = new javax.swing.JRadioButton();
        BtnNbrPlatMs = new javax.swing.JLabel();
        BtnElimMs = new javax.swing.JButton();
        TxtNumMs = new javax.swing.JTextField();
        BtnGdrMs = new javax.swing.JButton();
        TxtidMs = new javax.swing.JTextField();
        BxNmbrPlatMs = new javax.swing.JComboBox<>();
        BtnBuscarMs2 = new javax.swing.JButton();
        BtnBuscarMs3 = new javax.swing.JButton();
        BtnBuscarMs4 = new javax.swing.JButton();
        FrmNuestraHistoria = new javax.swing.JFrame();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        NbrRst = new javax.swing.JLabel();
        MsjRst = new javax.swing.JLabel();
        BarradeTareas = new javax.swing.JMenuBar();
        BtnTrMenu = new javax.swing.JMenu();
        BtnPlatos = new javax.swing.JMenuItem();
        BtnModifPlts = new javax.swing.JMenuItem();
        BtnTrArchivo = new javax.swing.JMenu();
        Empleados = new javax.swing.JMenuItem();
        BtnModifEmpleados = new javax.swing.JMenuItem();
        BtnTrMesas = new javax.swing.JMenu();
        BtnListarMesas = new javax.swing.JMenuItem();
        BtnModifMesas = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        LabCate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabCate.setText("Ingrese la Categoria :");

        GrpTxtCate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        GrpTxtCate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bebida", "Entrada", "Plato Fuerte", "Postre" }));

        TblPlatos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TblPlatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id Plato", "Nombre", "Precio", "Disponible"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TblPlatos);

        LblNumPlt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblNumPlt.setText("Numero de Platos :");

        LblPltDisp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblPltDisp.setText("Platillos Disponibles :");

        LblNumCuantos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblNumCuantos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblNumCuantos.setText("0");
        LblNumCuantos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        LblPlatCuantos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblPlatCuantos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblPlatCuantos.setText("0");
        LblPlatCuantos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout ListaPlatosLayout = new javax.swing.GroupLayout(ListaPlatos.getContentPane());
        ListaPlatos.getContentPane().setLayout(ListaPlatosLayout);
        ListaPlatosLayout.setHorizontalGroup(
            ListaPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaPlatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ListaPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
                    .addGroup(ListaPlatosLayout.createSequentialGroup()
                        .addGroup(ListaPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ListaPlatosLayout.createSequentialGroup()
                                .addComponent(LabCate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GrpTxtCate, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ListaPlatosLayout.createSequentialGroup()
                                .addGroup(ListaPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(LblPltDisp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LblNumPlt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(ListaPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LblNumCuantos, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LblPlatCuantos, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ListaPlatosLayout.setVerticalGroup(
            ListaPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaPlatosLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(ListaPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LabCate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GrpTxtCate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ListaPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblNumPlt)
                    .addComponent(LblNumCuantos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ListaPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblPltDisp)
                    .addComponent(LblPlatCuantos))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        ModifPlatos.setTitle("Modificar Platos");
        ModifPlatos.setResizable(false);

        IdPlatos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        IdPlatos.setText("Id Plato");

        Nombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Nombre.setText("Nombre ");

        Categoria.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Categoria.setText("Categoria");

        Precio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Precio.setText("Precio");

        TxtNombre.setEnabled(false);
        TxtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombreActionPerformed(evt);
            }
        });

        TxtPrecio.setEnabled(false);
        TxtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPrecioActionPerformed(evt);
            }
        });

        BtnBuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnBuscar.setText("Buscar");
        BtnBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Disponible.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Disponible.setText("Disponible");

        GrpDispo.add(BtnDisponible);
        BtnDisponible.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnDisponible.setText("Disponible");
        BtnDisponible.setEnabled(false);
        BtnDisponible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDisponibleActionPerformed(evt);
            }
        });

        GrpDispo.add(BtnNoDisponible);
        BtnNoDisponible.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnNoDisponible.setText("No Disponible");
        BtnNoDisponible.setEnabled(false);

        BxCategoria.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bebida", "Entrada", "Plato Fuerte", "Postre" }));
        BxCategoria.setEnabled(false);

        BtnGrdr.setText("Guardar Cambios");
        BtnGrdr.setEnabled(false);

        TxtTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TxtTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtTitulo.setText("Modificar Platos");

        BtnModifCmb.setText("Modificar Cambios");
        BtnModifCmb.setEnabled(false);

        BtnElimCmb.setText("Eliminar Cambios");
        BtnElimCmb.setEnabled(false);

        javax.swing.GroupLayout ModifPlatosLayout = new javax.swing.GroupLayout(ModifPlatos.getContentPane());
        ModifPlatos.getContentPane().setLayout(ModifPlatosLayout);
        ModifPlatosLayout.setHorizontalGroup(
            ModifPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModifPlatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ModifPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModifPlatosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(ModifPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Disponible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(IdPlatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Categoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Precio, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ModifPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(ModifPlatosLayout.createSequentialGroup()
                                .addComponent(TxtId, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnBuscar))
                            .addComponent(TxtNombre)
                            .addComponent(TxtPrecio, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ModifPlatosLayout.createSequentialGroup()
                                .addComponent(BtnDisponible)
                                .addGap(18, 18, 18)
                                .addComponent(BtnNoDisponible))
                            .addComponent(BxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModifPlatosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ModifPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnElimCmb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnModifCmb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnGrdr, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        ModifPlatosLayout.setVerticalGroup(
            ModifPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModifPlatosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(TxtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ModifPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TxtId)
                    .addComponent(IdPlatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ModifPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ModifPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ModifPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Precio, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ModifPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(Disponible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnDisponible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnNoDisponible))
                .addGap(18, 18, 18)
                .addComponent(BtnGrdr, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnModifCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnElimCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        Nombre1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Nombre1.setText("Nombre ");

        GrpDispo.add(BtnNo);
        BtnNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnNo.setText("No");
        BtnNo.setEnabled(false);

        Tarea.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Tarea.setText("Tarea");

        BxTarea.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BxTarea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerente", "Mesero", "Cocinero", "Catador", "Recepcionista", "Limpiador" }));
        BxTarea.setEnabled(false);

        Turno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Turno.setText("Turno");

        TxtId1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtId1ActionPerformed(evt);
            }
        });

        BtnGrdr1.setText("Guardar Cambios");
        BtnGrdr1.setEnabled(false);

        TxtNombre1.setEnabled(false);
        TxtNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombre1ActionPerformed(evt);
            }
        });

        TxtTurno1.setEnabled(false);
        TxtTurno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTurno1ActionPerformed(evt);
            }
        });

        BtnBuscar1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnBuscar1.setText("Buscar");
        BtnBuscar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscar1ActionPerformed(evt);
            }
        });

        TxtTitulo1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TxtTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtTitulo1.setText("Modificar Empleados");

        Presente1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Presente1.setText("Presente");

        BtnModifCmb1.setText("Modificar Cambios");
        BtnModifCmb1.setEnabled(false);

        IdEmpleados1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        IdEmpleados1.setText("Id Empleado");

        GrpDispo.add(BtnSi1);
        BtnSi1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnSi1.setText("Si");
        BtnSi1.setEnabled(false);
        BtnSi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSi1ActionPerformed(evt);
            }
        });

        BtnElimCmb1.setText("Eliminar Cambios");
        BtnElimCmb1.setEnabled(false);

        javax.swing.GroupLayout ModifEmpleadosLayout = new javax.swing.GroupLayout(ModifEmpleados.getContentPane());
        ModifEmpleados.getContentPane().setLayout(ModifEmpleadosLayout);
        ModifEmpleadosLayout.setHorizontalGroup(
            ModifEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModifEmpleadosLayout.createSequentialGroup()
                .addGroup(ModifEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModifEmpleadosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(ModifEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtnGrdr1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ModifEmpleadosLayout.createSequentialGroup()
                                .addGroup(ModifEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Presente1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Nombre1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Tarea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Turno, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ModifEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(ModifEmpleadosLayout.createSequentialGroup()
                                        .addComponent(BtnSi1)
                                        .addGap(18, 18, 18)
                                        .addComponent(BtnNo))
                                    .addComponent(BxTarea, 0, 290, Short.MAX_VALUE)
                                    .addComponent(TxtNombre1)
                                    .addComponent(TxtTurno1))))
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModifEmpleadosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ModifEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtTitulo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModifEmpleadosLayout.createSequentialGroup()
                                .addGap(0, 6, Short.MAX_VALUE)
                                .addGroup(ModifEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModifEmpleadosLayout.createSequentialGroup()
                                        .addComponent(IdEmpleados1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtId1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnBuscar1)
                                        .addGap(67, 67, 67))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModifEmpleadosLayout.createSequentialGroup()
                                        .addGroup(ModifEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(BtnModifCmb1, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                                            .addComponent(BtnElimCmb1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(10, 10, 10)))))))
                .addContainerGap())
        );
        ModifEmpleadosLayout.setVerticalGroup(
            ModifEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModifEmpleadosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(TxtTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ModifEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ModifEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(IdEmpleados1, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                        .addComponent(TxtId1))
                    .addGroup(ModifEmpleadosLayout.createSequentialGroup()
                        .addComponent(BtnBuscar1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ModifEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Nombre1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TxtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ModifEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tarea, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BxTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ModifEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Turno, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtTurno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ModifEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(Presente1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnSi1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnGrdr1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnModifCmb1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnElimCmb1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        ListarMesas.setTitle("Lista Mesas");
        ListarMesas.setResizable(false);

        NbrMesa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NbrMesa.setText("Ingrese el Numero de Mesa:");

        TxtNbrMesa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TxtNbrMesa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        EliOrdenMesa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        EliOrdenMesa.setText("Buscar");

        TblOrdn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TblOrdn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TblOrdn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Ordenes", "Sillas Ocupadas", "Mesero Asignado", "Pedidos Especiales"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TblOrdn.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TblOrdn);

        CantPed.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CantPed.setText("Cantidad Total de Pedidos :");

        TermiServ.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TermiServ.setText("Termino el Servicio :");

        GrpTermi.add(BtnTermiSi);
        BtnTermiSi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnTermiSi.setText("Si");
        BtnTermiSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTermiSiActionPerformed(evt);
            }
        });

        GrpTermi.add(BtnTermiNo);
        BtnTermiNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnTermiNo.setText("No");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("0");

        EliOrdenMesa1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        EliOrdenMesa1.setText("Eliminar");

        javax.swing.GroupLayout ListarMesasLayout = new javax.swing.GroupLayout(ListarMesas.getContentPane());
        ListarMesas.getContentPane().setLayout(ListarMesasLayout);
        ListarMesasLayout.setHorizontalGroup(
            ListarMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListarMesasLayout.createSequentialGroup()
                .addGroup(ListarMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ListarMesasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(ListarMesasLayout.createSequentialGroup()
                        .addGroup(ListarMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ListarMesasLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(ListarMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CantPed, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                    .addComponent(TermiServ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ListarMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(ListarMesasLayout.createSequentialGroup()
                                        .addComponent(BtnTermiSi, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(BtnTermiNo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(ListarMesasLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(NbrMesa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtNbrMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EliOrdenMesa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EliOrdenMesa1)))
                        .addGap(0, 339, Short.MAX_VALUE)))
                .addContainerGap())
        );

        ListarMesasLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {EliOrdenMesa, EliOrdenMesa1});

        ListarMesasLayout.setVerticalGroup(
            ListarMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListarMesasLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(ListarMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NbrMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListarMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TxtNbrMesa)
                        .addComponent(EliOrdenMesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EliOrdenMesa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ListarMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CantPed)
                    .addComponent(jLabel1))
                .addGap(12, 12, 12)
                .addGroup(ListarMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ListarMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BtnTermiSi, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(BtnTermiNo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(TermiServ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        ListarMesasLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {EliOrdenMesa, EliOrdenMesa1, NbrMesa, TxtNbrMesa});

        ModifMesas.setResizable(false);

        BtnBuscarMs1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnBuscarMs1.setText("Buscar");
        BtnBuscarMs1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnBuscarMs1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarMs1ActionPerformed(evt);
            }
        });

        LblTitMs.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LblTitMs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblTitMs.setText("Modificar Mesas");

        LblidMs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblidMs.setText("Id Mesero");
        LblidMs.setEnabled(false);

        LblOcpMs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblOcpMs.setText("Ocupada");
        LblOcpMs.setEnabled(false);

        GrpDispo.add(BtnMsNo);
        BtnMsNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnMsNo.setText("No");
        BtnMsNo.setEnabled(false);

        BtnModifMs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnModifMs.setText("Modificar Cambios");
        BtnModifMs.setEnabled(false);
        BtnModifMs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModifMsActionPerformed(evt);
            }
        });

        LblCatMs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblCatMs.setText("Categoria");
        LblCatMs.setEnabled(false);

        LblNumMs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblNumMs.setText("Numero de Mesa");

        BxCatMs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BxCatMs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bebida", "Entrada", "Plato Fuerte", "Postre" }));
        BxCatMs.setEnabled(false);
        BxCatMs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BxCatMsActionPerformed(evt);
            }
        });

        GrpDispo.add(BtnMsSi);
        BtnMsSi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnMsSi.setText("Si");
        BtnMsSi.setEnabled(false);
        BtnMsSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMsSiActionPerformed(evt);
            }
        });

        BtnNbrPlatMs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnNbrPlatMs.setText("Nombre");
        BtnNbrPlatMs.setEnabled(false);

        BtnElimMs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnElimMs.setText("Eliminar Cambios");
        BtnElimMs.setEnabled(false);
        BtnElimMs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnElimMsActionPerformed(evt);
            }
        });

        TxtNumMs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNumMsActionPerformed(evt);
            }
        });

        BtnGdrMs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnGdrMs.setText("Guardar Cambios");
        BtnGdrMs.setEnabled(false);

        TxtidMs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TxtidMs.setEnabled(false);
        TxtidMs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtidMsActionPerformed(evt);
            }
        });

        BxNmbrPlatMs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BxNmbrPlatMs.setEnabled(false);

        BtnBuscarMs2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnBuscarMs2.setText("Buscar");
        BtnBuscarMs2.setEnabled(false);
        BtnBuscarMs2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnBuscarMs2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarMs2ActionPerformed(evt);
            }
        });

        BtnBuscarMs3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnBuscarMs3.setText("Buscar");
        BtnBuscarMs3.setEnabled(false);
        BtnBuscarMs3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnBuscarMs3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarMs3ActionPerformed(evt);
            }
        });

        BtnBuscarMs4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnBuscarMs4.setText("Buscar");
        BtnBuscarMs4.setEnabled(false);
        BtnBuscarMs4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnBuscarMs4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarMs4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ModifMesasLayout = new javax.swing.GroupLayout(ModifMesas.getContentPane());
        ModifMesas.getContentPane().setLayout(ModifMesasLayout);
        ModifMesasLayout.setHorizontalGroup(
            ModifMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModifMesasLayout.createSequentialGroup()
                .addGroup(ModifMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ModifMesasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LblTitMs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ModifMesasLayout.createSequentialGroup()
                        .addGroup(ModifMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ModifMesasLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(ModifMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BtnNbrPlatMs, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LblCatMs, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LblidMs, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ModifMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BxCatMs, 0, 238, Short.MAX_VALUE)
                                    .addComponent(BxNmbrPlatMs, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TxtidMs)))
                            .addGroup(ModifMesasLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(LblNumMs)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtNumMs)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ModifMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnBuscarMs1)
                            .addComponent(BtnBuscarMs2)
                            .addComponent(BtnBuscarMs3)
                            .addComponent(BtnBuscarMs4))
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModifMesasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(ModifMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnGdrMs, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModifMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(BtnModifMs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnElimMs, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)))
                .addContainerGap())
            .addGroup(ModifMesasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblOcpMs, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnMsSi)
                .addGap(18, 18, 18)
                .addComponent(BtnMsNo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ModifMesasLayout.setVerticalGroup(
            ModifMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModifMesasLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(LblTitMs, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ModifMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ModifMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LblNumMs, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                        .addComponent(TxtNumMs))
                    .addGroup(ModifMesasLayout.createSequentialGroup()
                        .addComponent(BtnBuscarMs1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ModifMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ModifMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TxtidMs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LblidMs))
                    .addComponent(BtnBuscarMs2))
                .addGap(3, 3, 3)
                .addGroup(ModifMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BxCatMs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblCatMs, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBuscarMs3))
                .addGap(7, 7, 7)
                .addGroup(ModifMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnNbrPlatMs)
                    .addComponent(BxNmbrPlatMs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBuscarMs4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ModifMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblOcpMs)
                    .addGroup(ModifMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                        .addComponent(BtnMsSi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnMsNo)))
                .addGap(21, 21, 21)
                .addComponent(BtnGdrMs, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnModifMs, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnElimMs, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        ModifMesasLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {BtnNbrPlatMs, LblCatMs, LblOcpMs, LblidMs});

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Quienes Somos");

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField1.setText("¡Bienvenidos a Kazza!  En Kazza, nos apasiona la pizza y la autenticidad. Desde nuestro primer día, nos hemos comprometido a ofrecer a nuestros clientes una experiencia gastronómica inigualable, donde cada bocado es un viaje a las tradiciones más auténticas de la cocina italiana.  Nuestro equipo de chefs, con años de experiencia y dedicación, se esfuerza por crear pizzas artesanales utilizando ingredientes frescos y de la más alta calidad. Desde la masa hecha a mano hasta las salsas caseras y los toppings cuidadosamente seleccionados, cada detalle es importante para nosotros.  Más allá de la comida, en [Nombre del Restaurante] nos enorgullece brindar un ambiente acogedor y familiar. Queremos que cada visita se sienta como estar en casa, rodeado de buena comida y buena compañía. Nuestro personal amable y atento está siempre dispuesto a hacer de su visita una experiencia memorable.  Ya sea que venga a disfrutar de una comida rápida y deliciosa, a celebrar una ocasión especial, o simplemente a relajarse con amigos y familia, en [Nombre del Restaurante] encontrará siempre el sabor, el servicio y la calidez que nos caracteriza.  Gracias por elegirnos y permitirnos ser parte de sus momentos especiales. ¡Esperamos verle pronto y compartir juntos nuestra pasión por la pizza!  Con gratitud, El equipo de [Nombre del Restaurante]");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FrmNuestraHistoriaLayout = new javax.swing.GroupLayout(FrmNuestraHistoria.getContentPane());
        FrmNuestraHistoria.getContentPane().setLayout(FrmNuestraHistoriaLayout);
        FrmNuestraHistoriaLayout.setHorizontalGroup(
            FrmNuestraHistoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrmNuestraHistoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FrmNuestraHistoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE))
                .addContainerGap())
        );
        FrmNuestraHistoriaLayout.setVerticalGroup(
            FrmNuestraHistoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrmNuestraHistoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kazza");
        setBackground(new java.awt.Color(0, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        NbrRst.setFont(new java.awt.Font("Imprint MT Shadow", 1, 48)); // NOI18N
        NbrRst.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NbrRst.setText("Kazza");

        MsjRst.setFont(new java.awt.Font("Imprint MT Shadow", 1, 18)); // NOI18N
        MsjRst.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MsjRst.setText("L'autentico sapore italiano");

        BarradeTareas.setBackground(new java.awt.Color(51, 51, 51));
        BarradeTareas.setForeground(new java.awt.Color(0, 0, 0));

        BtnTrMenu.setBackground(new java.awt.Color(255, 255, 255));
        BtnTrMenu.setForeground(new java.awt.Color(0, 0, 0));
        BtnTrMenu.setText("Menu");
        BtnTrMenu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        BtnPlatos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        BtnPlatos.setText("Lista de Platos");
        BtnPlatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPlatosActionPerformed(evt);
            }
        });
        BtnTrMenu.add(BtnPlatos);

        BtnModifPlts.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        BtnModifPlts.setText("Modificar Platos");
        BtnModifPlts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModifPltsActionPerformed(evt);
            }
        });
        BtnTrMenu.add(BtnModifPlts);

        BarradeTareas.add(BtnTrMenu);

        BtnTrArchivo.setBackground(new java.awt.Color(255, 255, 255));
        BtnTrArchivo.setForeground(new java.awt.Color(0, 0, 0));
        BtnTrArchivo.setText("Archivo");
        BtnTrArchivo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        Empleados.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Empleados.setText("Empleados");
        BtnTrArchivo.add(Empleados);

        BtnModifEmpleados.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        BtnModifEmpleados.setText("Modificar Empleados");
        BtnModifEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModifEmpleadosActionPerformed(evt);
            }
        });
        BtnTrArchivo.add(BtnModifEmpleados);

        BarradeTareas.add(BtnTrArchivo);

        BtnTrMesas.setText("Mesas");
        BtnTrMesas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnTrMesas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        BtnListarMesas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        BtnListarMesas.setText("Listar Mesas");
        BtnListarMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnListarMesasActionPerformed(evt);
            }
        });
        BtnTrMesas.add(BtnListarMesas);

        BtnModifMesas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        BtnModifMesas.setText("Modificar Mesas");
        BtnModifMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModifMesasActionPerformed(evt);
            }
        });
        BtnTrMesas.add(BtnModifMesas);

        BarradeTareas.add(BtnTrMesas);

        jMenu1.setText("Quienes Somos");
        jMenu1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Nuestra Historia");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setText("Contactenos");
        jMenu1.add(jMenuItem2);

        BarradeTareas.add(jMenu1);

        setJMenuBar(BarradeTareas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addComponent(MsjRst, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(NbrRst, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(NbrRst, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MsjRst, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnModifPltsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModifPltsActionPerformed
        ModifPlatos.setVisible(true);
    }//GEN-LAST:event_BtnModifPltsActionPerformed

    private void BtnModifEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModifEmpleadosActionPerformed
        ModifEmpleados.setVisible(true);
    }//GEN-LAST:event_BtnModifEmpleadosActionPerformed

    private void TxtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrecioActionPerformed

    private void TxtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNombreActionPerformed

    private void BtnDisponibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDisponibleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnDisponibleActionPerformed

    private void TxtNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNombre1ActionPerformed

    private void TxtTurno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTurno1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTurno1ActionPerformed

    private void BtnSi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSi1ActionPerformed

    private void TxtId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtId1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtId1ActionPerformed

    private void BtnBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnBuscar1ActionPerformed

    private void BtnListarMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnListarMesasActionPerformed
        ListarMesas.setVisible(true);
    }//GEN-LAST:event_BtnListarMesasActionPerformed

    private void BtnTermiSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTermiSiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnTermiSiActionPerformed

    private void BtnPlatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPlatosActionPerformed
        ListaPlatos.setVisible(true);
    }//GEN-LAST:event_BtnPlatosActionPerformed

    private void BtnModifMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModifMesasActionPerformed
        ModifMesas.setVisible(true);
    }//GEN-LAST:event_BtnModifMesasActionPerformed

    private void BtnBuscarMs1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarMs1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnBuscarMs1ActionPerformed

    private void BtnMsSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMsSiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnMsSiActionPerformed

    private void TxtNumMsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNumMsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNumMsActionPerformed

    private void TxtidMsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtidMsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtidMsActionPerformed

    private void BtnBuscarMs2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarMs2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnBuscarMs2ActionPerformed

    private void BtnBuscarMs3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarMs3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnBuscarMs3ActionPerformed

    private void BtnBuscarMs4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarMs4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnBuscarMs4ActionPerformed

    private void BxCatMsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BxCatMsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BxCatMsActionPerformed

    private void BtnModifMsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModifMsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnModifMsActionPerformed

    private void BtnElimMsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnElimMsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnElimMsActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FrmNuestraHistoria.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarradeTareas;
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnBuscar1;
    private javax.swing.JButton BtnBuscarMs1;
    private javax.swing.JButton BtnBuscarMs2;
    private javax.swing.JButton BtnBuscarMs3;
    private javax.swing.JButton BtnBuscarMs4;
    private javax.swing.JRadioButton BtnDisponible;
    private javax.swing.JButton BtnElimCmb;
    private javax.swing.JButton BtnElimCmb1;
    private javax.swing.JButton BtnElimMs;
    private javax.swing.JButton BtnGdrMs;
    private javax.swing.JButton BtnGrdr;
    private javax.swing.JButton BtnGrdr1;
    private javax.swing.JMenuItem BtnListarMesas;
    private javax.swing.JButton BtnModifCmb;
    private javax.swing.JButton BtnModifCmb1;
    private javax.swing.JMenuItem BtnModifEmpleados;
    private javax.swing.JMenuItem BtnModifMesas;
    private javax.swing.JButton BtnModifMs;
    private javax.swing.JMenuItem BtnModifPlts;
    private javax.swing.JRadioButton BtnMsNo;
    private javax.swing.JRadioButton BtnMsSi;
    private javax.swing.JLabel BtnNbrPlatMs;
    private javax.swing.JRadioButton BtnNo;
    private javax.swing.JRadioButton BtnNoDisponible;
    private javax.swing.JMenuItem BtnPlatos;
    private javax.swing.JRadioButton BtnSi1;
    private javax.swing.JRadioButton BtnTermiNo;
    private javax.swing.JRadioButton BtnTermiSi;
    private javax.swing.JMenu BtnTrArchivo;
    private javax.swing.JMenu BtnTrMenu;
    private javax.swing.JMenu BtnTrMesas;
    private javax.swing.JComboBox<String> BxCatMs;
    private javax.swing.JComboBox<String> BxCategoria;
    private javax.swing.JComboBox<String> BxNmbrPlatMs;
    private javax.swing.JComboBox<String> BxTarea;
    private javax.swing.JLabel CantPed;
    private javax.swing.JLabel Categoria;
    private javax.swing.JLabel Disponible;
    private javax.swing.JToggleButton EliOrdenMesa;
    private javax.swing.JToggleButton EliOrdenMesa1;
    private javax.swing.JMenuItem Empleados;
    private javax.swing.JFrame FrmNuestraHistoria;
    private javax.swing.ButtonGroup GrpDispo;
    private javax.swing.ButtonGroup GrpTermi;
    private javax.swing.JComboBox<String> GrpTxtCate;
    private javax.swing.JLabel IdEmpleados1;
    private javax.swing.JLabel IdPlatos;
    private javax.swing.JLabel LabCate;
    private javax.swing.JLabel LblCatMs;
    private javax.swing.JLabel LblNumCuantos;
    private javax.swing.JLabel LblNumMs;
    private javax.swing.JLabel LblNumPlt;
    private javax.swing.JLabel LblOcpMs;
    private javax.swing.JLabel LblPlatCuantos;
    private javax.swing.JLabel LblPltDisp;
    private javax.swing.JLabel LblTitMs;
    private javax.swing.JLabel LblidMs;
    private javax.swing.JFrame ListaPlatos;
    private javax.swing.JFrame ListarMesas;
    private javax.swing.JFrame ModifEmpleados;
    private javax.swing.JFrame ModifMesas;
    private javax.swing.JFrame ModifPlatos;
    private javax.swing.JLabel MsjRst;
    private javax.swing.JLabel NbrMesa;
    private javax.swing.JLabel NbrRst;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Nombre1;
    private javax.swing.JLabel Precio;
    private javax.swing.JLabel Presente1;
    private javax.swing.JLabel Tarea;
    private javax.swing.JTable TblOrdn;
    private javax.swing.JTable TblPlatos;
    private javax.swing.JLabel TermiServ;
    private javax.swing.JLabel Turno;
    private javax.swing.JTextField TxtId;
    private javax.swing.JTextField TxtId1;
    private javax.swing.JTextField TxtNbrMesa;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtNombre1;
    private javax.swing.JTextField TxtNumMs;
    private javax.swing.JTextField TxtPrecio;
    private javax.swing.JLabel TxtTitulo;
    private javax.swing.JLabel TxtTitulo1;
    private javax.swing.JTextField TxtTurno1;
    private javax.swing.JTextField TxtidMs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
